# Generated by Django 5.0.6 on 2024-06-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousedelivery',
            name='country',
            field=models.CharField(default='Default Country', max_length=100),
        ),
    ]
