# Generated by Django 5.0.6 on 2024-06-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_warehousedelivery_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousedelivery',
            name='product_name1',
            field=models.CharField(default='Warehouse Delivery', max_length=100),
        ),
        migrations.AddField(
            model_name='warehousedelivery',
            name='product_name2',
            field=models.CharField(default='Warehouse Delivery', max_length=100),
        ),
        migrations.AlterField(
            model_name='warehousedelivery',
            name='product_name',
            field=models.CharField(default='Warehouse Delivery', max_length=100),
        ),
    ]
