# Generated by Django 5.0.6 on 2024-06-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_warehousedelivery_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousedelivery',
            name='quantity',
        ),
    ]
