# Generated by Django 5.0.6 on 2024-06-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_warehousedelivery_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousedelivery',
            name='product_name',
        ),
    ]
