# Generated by Django 5.0.6 on 2024-06-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_warehousedelivery_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousedelivery',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
