# Generated by Django 5.0.6 on 2024-06-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_warehousedelivery_product_name1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousedelivery',
            name='country1',
            field=models.SlugField(choices=[('PL', 'Polska'), ('DE', 'Niemcy'), ('FR', 'Francja'), ('ES', 'Hiszpania'), ('IT', 'Włochy')], default='PL', max_length=200),
        ),
        migrations.AddField(
            model_name='warehousedelivery',
            name='country2',
            field=models.SlugField(choices=[('PL', 'Polska'), ('DE', 'Niemcy'), ('FR', 'Francja'), ('ES', 'Hiszpania'), ('IT', 'Włochy')], default='PL', max_length=200),
        ),
    ]
