# Generated by Django 5.0.6 on 2024-06-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_warehousedelivery_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousedelivery',
            name='country3',
            field=models.SlugField(choices=[('PL', 'Polska'), ('DE', 'Niemcy'), ('FR', 'Francja'), ('ES', 'Hiszpania'), ('IT', 'Włochy')], default='PL', max_length=200),
        ),
        migrations.AddField(
            model_name='warehousedelivery',
            name='country4',
            field=models.SlugField(choices=[('PL', 'Polska'), ('DE', 'Niemcy'), ('FR', 'Francja'), ('ES', 'Hiszpania'), ('IT', 'Włochy')], default='PL', max_length=200),
        ),
        migrations.AddField(
            model_name='warehousedelivery',
            name='country5',
            field=models.SlugField(choices=[('PL', 'Polska'), ('DE', 'Niemcy'), ('FR', 'Francja'), ('ES', 'Hiszpania'), ('IT', 'Włochy')], default='PL', max_length=200),
        ),
        migrations.AddField(
            model_name='warehousedelivery',
            name='country6',
            field=models.SlugField(choices=[('PL', 'Polska'), ('DE', 'Niemcy'), ('FR', 'Francja'), ('ES', 'Hiszpania'), ('IT', 'Włochy')], default='PL', max_length=200),
        ),
        migrations.AddField(
            model_name='warehousedelivery',
            name='product_name3',
            field=models.CharField(default='WarhouseDelivery', max_length=100),
        ),
        migrations.AddField(
            model_name='warehousedelivery',
            name='product_name4',
            field=models.CharField(default='WarhouseDelivery', max_length=100),
        ),
        migrations.AddField(
            model_name='warehousedelivery',
            name='product_name5',
            field=models.CharField(default='WarhouseDelivery', max_length=100),
        ),
        migrations.AddField(
            model_name='warehousedelivery',
            name='product_name6',
            field=models.CharField(default='WarhouseDelivery', max_length=100),
        ),
        migrations.AddField(
            model_name='warehousedelivery',
            name='quantity3',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehousedelivery',
            name='quantity4',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehousedelivery',
            name='quantity5',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
