# Generated by Django 5.0.6 on 2024-06-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_warehousedelivery_country3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousedelivery',
            name='country3',
            field=models.SlugField(choices=[('PL', 'Polska'), ('DE', 'Niemcy'), ('FR', 'Francja'), ('ES', 'Hiszpania'), ('IT', 'Włochy')], max_length=200),
        ),
        migrations.AlterField(
            model_name='warehousedelivery',
            name='country4',
            field=models.SlugField(choices=[('PL', 'Polska'), ('DE', 'Niemcy'), ('FR', 'Francja'), ('ES', 'Hiszpania'), ('IT', 'Włochy')], max_length=200),
        ),
        migrations.AlterField(
            model_name='warehousedelivery',
            name='country5',
            field=models.SlugField(choices=[('PL', 'Polska'), ('DE', 'Niemcy'), ('FR', 'Francja'), ('ES', 'Hiszpania'), ('IT', 'Włochy')], max_length=200),
        ),
        migrations.AlterField(
            model_name='warehousedelivery',
            name='country6',
            field=models.SlugField(choices=[('PL', 'Polska'), ('DE', 'Niemcy'), ('FR', 'Francja'), ('ES', 'Hiszpania'), ('IT', 'Włochy')], max_length=200),
        ),
        migrations.AlterField(
            model_name='warehousedelivery',
            name='product_name3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='warehousedelivery',
            name='product_name4',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='warehousedelivery',
            name='product_name5',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='warehousedelivery',
            name='product_name6',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='warehousedelivery',
            name='quantity3',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='warehousedelivery',
            name='quantity4',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='warehousedelivery',
            name='quantity5',
            field=models.PositiveIntegerField(),
        ),
    ]
