# Generated by Django 5.0.6 on 2024-06-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_remove_warehousedelivery_country6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousedelivery',
            name='name',
            field=models.CharField(default='Warehouse Delivery', max_length=100),
        ),
    ]
