# Generated by Django 5.0.6 on 2024-06-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_warehousedelivery_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousedelivery',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
