# Generated by Django 5.0.6 on 2024-06-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_alter_warehousedelivery_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=100)),
                ('arrival_date', models.DateField()),
                ('ship_type', models.CharField(max_length=100)),
            ],
        ),
    ]
