# Generated by Django 5.0.6 on 2024-06-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_container_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
