# Generated by Django 5.0.6 on 2024-06-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_rename_amount_container_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='sum',
            field=models.CharField(max_length=100),
        ),
    ]
