# Generated by Django 5.0.6 on 2024-06-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_alter_container_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='container_id',
            new_name='container_code',
        ),
    ]
