# Generated by Django 5.0.6 on 2024-06-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_rename_container_id_container_container_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousedelivery',
            name='country',
            field=models.CharField(choices=[('PL', 'Polska'), ('DE', 'Niemcy'), ('FR', 'Francja'), ('ES', 'Hiszpania'), ('IT', 'Włochy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='warehousedelivery',
            name='country1',
            field=models.CharField(choices=[('PL', 'Polska'), ('DE', 'Niemcy'), ('FR', 'Francja'), ('ES', 'Hiszpania'), ('IT', 'Włochy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='warehousedelivery',
            name='country2',
            field=models.CharField(choices=[('PL', 'Polska'), ('DE', 'Niemcy'), ('FR', 'Francja'), ('ES', 'Hiszpania'), ('IT', 'Włochy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='warehousedelivery',
            name='country3',
            field=models.CharField(choices=[('PL', 'Polska'), ('DE', 'Niemcy'), ('FR', 'Francja'), ('ES', 'Hiszpania'), ('IT', 'Włochy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='warehousedelivery',
            name='country4',
            field=models.CharField(choices=[('PL', 'Polska'), ('DE', 'Niemcy'), ('FR', 'Francja'), ('ES', 'Hiszpania'), ('IT', 'Włochy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='warehousedelivery',
            name='country5',
            field=models.CharField(choices=[('PL', 'Polska'), ('DE', 'Niemcy'), ('FR', 'Francja'), ('ES', 'Hiszpania'), ('IT', 'Włochy')], max_length=100),
        ),
    ]
