# Generated by Django 5.0.6 on 2024-06-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_alter_warehousedelivery_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousedelivery',
            name='country',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='warehousedelivery',
            name='country1',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='warehousedelivery',
            name='country2',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='warehousedelivery',
            name='country3',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='warehousedelivery',
            name='country4',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='warehousedelivery',
            name='country5',
            field=models.SlugField(max_length=200),
        ),
    ]
