# Generated by Django 5.0.6 on 2024-06-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_alter_warehousedelivery_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousedelivery',
            name='country1',
            field=models.CharField(max_length=100),
        ),
    ]
