# Generated by Django 5.0.6 on 2024-06-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_container_container_code1_container_container_code2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='ship_type1',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='container',
            name='ship_type2',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='container',
            name='ship_type3',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='container',
            name='ship_type4',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='container',
            name='ship_type5',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
