# Generated by Django 5.0.6 on 2024-06-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_container_ship_type1_container_ship_type2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seaports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('port1', models.CharField(default='working', max_length=100)),
                ('port2', models.CharField(default='working', max_length=100)),
                ('port3', models.CharField(default='working', max_length=100)),
                ('port4', models.CharField(default='working', max_length=100)),
                ('port5', models.CharField(default='working', max_length=100)),
                ('port6', models.CharField(default='working', max_length=100)),
            ],
        ),
    ]
