# Generated by Django 5.0.6 on 2024-06-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_seaportsstatuses_alter_seaports_name_seaports_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousedelivery',
            name='seaports',
            field=models.ManyToManyField(related_name='dostawy_magazynowe', to='myapp.seaports'),
        ),
    ]
