# Generated by Django 5.0.6 on 2024-06-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_remove_seaports_name_seaports_name1_seaports_name2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seaports',
            old_name='name1',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='seaports',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='seaports',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='seaports',
            name='name4',
        ),
        migrations.RemoveField(
            model_name='seaports',
            name='name5',
        ),
        migrations.RemoveField(
            model_name='seaports',
            name='name6',
        ),
    ]
