# Generated by Django 5.0.6 on 2024-06-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_alter_seaportsstatuses_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seaports',
            name='name',
        ),
    ]
