# Generated by Django 5.0.6 on 2024-06-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_remove_seaports_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, verbose_name='Nazwa produktu')),
                ('kategoria', models.CharField(choices=[('toys', 'Zabawki'), ('electronics', 'Energetyka'), ('building', 'Materiały budowlane'), ('chemicals', 'Chemikalia'), ('coal', 'Węgiel'), ('petroleum', 'Ropa naftowa')], max_length=50, verbose_name='Kategoria produktu')),
                ('ilosc', models.IntegerField(verbose_name='Ilość')),
                ('waga', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Waga (kg)')),
                ('kraj_docelowy', models.CharField(max_length=50, verbose_name='Kraj docelowy')),
                ('data_wysylki', models.DateField(verbose_name='Data wysyłki')),
                ('dodatkowe_uwagi', models.TextField(blank=True, verbose_name='Dodatkowe uwagi')),
            ],
        ),
    ]
